### ISSUE TITLE
Update to new 0.7

### ISSUE THREAD

**Issue by fabianluque** [fuatakgun/eufy_security_addon#2]
Bropat recently released a new 0.7 version that includes better support for Floodlight Cam Pro 2. 

Is there any chance you can update the add-on so we can use these new features?

**Comment by fuatakgun** [comment]
Please let me try first locally i will publish today or tomorrow latest.

**Comment by mikedrawback** [comment]
I've been testing 0.7.0 to see if it would fix the problem I had with p2p streaming for the older floodlight model T8420 and it fixed the issue for me! So far I haven't encountered any issues.

**Comment by fabianluque** [comment]
@fuatakgun Did you have some time to test this on your side?

**Comment by fuatakgun** [comment]
done
