### ISSUE TITLE
Reflect names of custom states on alarm panes

### ISSUE THREAD

**Issue by ShayGus** [fuatakgun/eufy_security_addon#4]
Right now the predefined states on the alarm pannel are out of sync with what the app is actually ofering.
For example Night isn't available on the app.
Also when defining custom states in the appl we give them names, so it would be great to be able to arm the alarm with those names.
In addition right now even without the names, custom alarm states such custom1 do net apear as an option to choose in the alarm panel.

**Comment by fuatakgun** [comment]
merging into https://github.com/fuatakgun/eufy_security/issues/145
